-- Privilegios

-- Privilegios sobre la cuenta 1

GRANT ALL ON CLIENTE TO PLATANO4, PLATANO2, PLATANO3;
GRANT ALL ON EMPLEADO TO PLATANO4, PLATANO2, PLATANO3;
GRANT ALL ON SUCURSALSOLICITASUCURSAL TO PLATANO4, PLATANO2, PLATANO3;
GRANT ALL ON PRODUCTOR TO PLATANO4, PLATANO2, PLATANO3;
GRANT ALL ON CLIENTESOLICITAVINOASUCURSAL TO PLATANO4, PLATANO2, PLATANO3;
GRANT ALL ON SUCURSAL TO PLATANO4, PLATANO2, PLATANO3;
GRANT ALL ON SUCURSALVENDEVINO TO PLATANO4, PLATANO2, PLATANO3;
GRANT ALL ON VINO TO PLATANO4, PLATANO2, PLATANO3;
COMMIT;

-- Privilegios sobre la cuenta 2
GRANT ALL ON CLIENTE TO PLATANO4, PLATANO1, PLATANO3;
GRANT ALL ON EMPLEADO TO PLATANO4, PLATANO1, PLATANO3;
GRANT ALL ON SUCURSALSOLICITASUCURSAL TO PLATANO4, PLATANO1, PLATANO3;
GRANT ALL ON PRODUCTOR TO PLATANO4, PLATANO1, PLATANO3;
GRANT ALL ON CLIENTESOLICITAVINOASUCURSAL TO PLATANO4, PLATANO1, PLATANO3;
GRANT ALL ON SUCURSAL TO PLATANO4, PLATANO1, PLATANO3;
GRANT ALL ON SUCURSALVENDEVINO TO PLATANO4, PLATANO1, PLATANO3;
GRANT ALL ON VINO TO PLATANO4, PLATANO1, PLATANO3;
COMMIT;

-- Privilegios sobre la cuenta 3
GRANT ALL ON CLIENTE TO PLATANO4, PLATANO1, PLATANO2;
GRANT ALL ON EMPLEADO TO PLATANO4, PLATANO1, PLATANO2;
GRANT ALL ON SUCURSALSOLICITASUCURSAL TO PLATANO4, PLATANO1, PLATANO2;
GRANT ALL ON PRODUCTOR TO PLATANO4, PLATANO1, PLATANO2;
GRANT ALL ON CLIENTESOLICITAVINOASUCURSAL TO PLATANO4, PLATANO1, PLATANO2;
GRANT ALL ON SUCURSAL TO PLATANO4, PLATANO1, PLATANO2;
GRANT ALL ON SUCURSALVENDEVINO TO PLATANO4, PLATANO1, PLATANO2;
GRANT ALL ON VINO TO PLATANO4, PLATANO1, PLATANO2;
COMMIT;

-- Privilegios sobre la cuenta 4
GRANT ALL ON CLIENTE TO PLATANO3, PLATANO1, PLATANO2;
GRANT ALL ON EMPLEADO TO PLATANO3, PLATANO1, PLATANO2;
GRANT ALL ON SUCURSALSOLICITASUCURSAL TO PLATANO3, PLATANO1, PLATANO2;
GRANT ALL ON PRODUCTOR TO PLATANO3, PLATANO1, PLATANO2;
GRANT ALL ON CLIENTESOLICITAVINOASUCURSAL TO PLATANO3, PLATANO1, PLATANO2;
GRANT ALL ON SUCURSAL TO PLATANO3, PLATANO1, PLATANO2;
GRANT ALL ON SUCURSALVENDEVINO TO PLATANO3, PLATANO1, PLATANO2;
GRANT ALL ON VINO TO PLATANO3, PLATANO1, PLATANO2;
COMMIT;
