SELECT * FROM SUCURSAL;
SELECT * FROM EMPLEADO;
SELECT * FROM VINO;
SELECT * FROM CLIENTE;
SELECT * FROM CLIENTESOLICITAVINOASUCURSAL;
SELECT * FROM PRODUCTOR;
SELECT * FROM SUCURSALSOLICITASUCURSAL;
SELECT * FROM SUCURSALVENDEVINO;
